server_addr: ":8765"
entity_id: "https://helsinki-rp.fedservice.lh"
organisation_name: "Helsinki University RP"
trust_anchors:
  - entity_id: "https://helsinki.fedservice.lh"
  - entity_id: "https://haka.fedservice.lh"
authority_hints:
  - "https://helsinki.fedservice.lh"
key_storage: /data
filter_to_automatic_ops: false
enable_debug_log: false

trust_marks:
  - trust_mark_type: "https://refeds.org/sirtfi"
    trust_mark_issuer: "https://surfconext.fedservice.lh"
  - trust_mark_type: "https://studid.io/federations/HAKA/member"
    trust_mark_issuer: "https://haka.fedservice.lh"
