server_port: 8765
entity_id: "https://incommon.fedservice.lh"
signing_key_file: "/data/signing.key"
organization_name: "Internet2 InCommon"
data_location: "/data/data"
human_readable_storage: true
metadata_policy_file: "/data/metadata-policy.json"
endpoints:
  fetch:
    path: "/fetch"
  list:
    path: "/list"
  resolve:
    path: "resolve"
  trust_mark:
    path: "/trustmark"
  trust_mark_status:
    path: "/trustmark/status"
  trust_mark_list:
    path: "/trustmark/list"
trust_mark_specs:
  - trust_mark_id: "https://refeds.org/sirtfi"
    lifetime: 86400
    ref: "https://refeds.org/wp-content/uploads/2022/08/Sirtfi-v2.pdf"
    delegation_jwt: %REFEDS_DELEGATION_JWT_INCOMMON%
    checker:
      type: none
  - trust_mark_id: "https://incommon.org/federation/member"
    lifetime: 86400
    ref: "https://incommon.org/federation/"
    checker:
      type: trust_path
      config:
        trust_anchors:
          - entity_id: "https://incommon.fedservice.lh"
trust_mark_issuers:
  https://incommon.org/federation/member:
    - "https://incommon.fedservice.lh"
trust_mark_owners:
  "https://refeds.org/sirtfi":
    jwks: %REFEDS_JWKS%
    entity_id: "https://refeds.fedservice.lh"
trust_marks:
  - trust_mark_id: "https://edugain.org/member"
    trust_mark_issuer: "https://edugain.fedservice.lh"
