server_port: 8765
entity_id: "https://puhuri.fedservice.lh"
signing_key_file: "/data/signing.key"
organization_name: "Puhuri VO"
data_location: "/data/data"
human_readable_storage: true
metadata_policy_file: "/data/metadata-policy.json"
endpoints:
  fetch:
    path: "/fetch"
  list:
    path: "/list"
  resolve:
    path: "resolve"
  trust_mark:
    path: "/trustmark"
  trust_mark_status:
    path: "/trustmark/status"
  trust_mark_list:
    path: "/trustmark/list"
trust_mark_specs:
  - trust_mark_id: "https://puhuri.io"
    lifetime: 86400
trust_mark_issuers:
  "https://puhuri.io":
    - "https://puhuri.fedservice.lh"
trust_marks:
  - trust_mark_id: "https://edugain.org/member"
    trust_mark_issuer: "https://edugain.fedservice.lh"
  - trust_mark_id: "https://puhuri.io"
    trust_mark_issuer: "https://puhuri.fedservice.lh"
  - trust_mark_id: "https://refeds.org/sirtfi"
    trust_mark_issuer: "https://haka.fedservice.lh"
  - trust_mark_id: "https://studid.io/federations/HAKA/member"
    trust_mark_issuer: "https://haka.fedservice.lh"
