server_port: 8765
entity_id: "https://ta.example.lh"
authority_hints:
  - "https://trust-anchor.spid-cie.fedservice.lh/"
signing_key_file: "/signing.key"
organization_name: "GO oidc-fed Intermediate"
data_location: "/data"
human_readable_storage: true
metadata_policy_file: "/metadata-policy.json"
endpoints:
  fetch:
    path: "/fetch"
  list:
    path: "/list"
  resolve:
    path: "/resolve"
  trust_mark:
    path: "/trustmark"
  trust_mark_status:
    path: "/trustmark/status"
  trust_mark_list:
    path: "/trustmark/list"
  enroll:
    path: "/enroll"
    checker:
      type: multiple_or
      config:
        - type: trust_mark
          config:
            trust_mark_id: https://tm.example.org
            trust_anchors:
              - entity_id: https://ta.example.org
        - type: trust_mark
          config:
            trust_mark_id: https://tm.example.com
            trust_anchors:
              - entity_id: https://example.com
              - entity_id: https://foo.bar.com
trust_mark_specs:
  - trust_mark_id: "https://tm.example.org"
    lifetime: 3600
    ref: "https://tm.example.org/ref"
    logo_uri: "https://tm.example.org/logo"
    extra_claim: "example"
    delegation_jwt:
  - trust_mark_id: "https://edugain.org"
    lifetime: 86400
